In [1]:
%load_ext Cython

import cython

import pstats, cProfile

import pyximport
pyximport.install(reload_support=True)

import Jfunc_cython_v4
from Jfunc_cython_v4 import computeJ as J
import numpy as np
import os
import sys
import config
import time
# from B222_jfunc_cython_v1 import compute_all_B222

In [6]:
from P22_jfunc_cython_v1 import compute_all_P22
from B222_jfunc_cython_v1 import compute_all_B222

In [2]:
# compute_all_P22()

In [3]:
# start_time = time.time()
# %prun -s cumulative compute_all_B222()
# print("time:", time.time()-start_time)

In [4]:
# start_time = time.time()
# compute_all_B222()
# print("time:", time.time()-start_time)

In [2]:
#from babiscython_v4_ubuntu import Ltrian as L
#from babiscython_v4_ubuntu import BubN
import gmpy2 as gm
from gmpy2 import *
# import time
gm.get_context().precision = 190
gm.get_context().allow_complex = True

# kpeak1 = -0.034
# kpeak2 = -0.001
# kpeak3 = -0.000076
# kpeak4 = -0.0000156
# kuv1 = 0.069
# kuv2 = 0.0082
# kuv3 = 0.0013
# kuv4 = 0.0000135
# kpeak1 = mpfr(str(kpeak1))
# kpeak2 = mpfr(str(kpeak2))
# kpeak3 = mpfr(str(kpeak3))
# kpeak4 = mpfr(str(kpeak4))
# kuv1 = mpfr(str(kuv1))
# kuv2 = mpfr(str(kuv2))
# kuv3 = mpfr(str(kuv3))
# kuv4 = mpfr(str(kuv4))

# mass1 = -kpeak1 - 1j*kuv1
# mass1conj = -kpeak1 + 1j*kuv1
# mass2 = -kpeak2 - 1j*kuv2
# mass2conj = -kpeak2 + 1j*kuv2
# mass3 = -kpeak3 - 1j*kuv3
# mass3conj = -kpeak3 + 1j*kuv3
# mass4 = -kpeak4 - 1j*kuv4
# mass4conj = -kpeak4 + 1j*kuv4

# k21 = mpfr(1.6)
# k22 = mpfr(1.25)
# k23 = mpfr(1.09)

# n1 = -3
# n2 = 2
# n3 = 1

# d1=2
# d2=3
# d3=2

# m1=mass1
# m2=mass2

In [3]:
# import scipy

# from scipy.special import gamma

In [18]:
# clear cache
config.Ltrian_cache.clear()
config.TriaN_cache.clear()

In [19]:
k21 = mpfr('0.1')**2
k22 = mpfr(0.199356)**2
k23 = mpfr(0.124006)**2

n1 = 0
n2 = 0
n3 = 0

d1= 0
d2= -1
d3= -1

J(n1,n2,n3,d1,d2,d3,k21,k22,k23)

-7.957747154594769e-08

In [ ]:
L(2,1,2,1,2,1,k21,k22,k23,mass1,mass2,mass1)

In [ ]:
def test_J():
    for i in range(16):
        J(n1,n2,n3,i,10,4,k21,k22,k23)

In [ ]:
lcs((1,2,3,4),(3,4,5,6))

In [ ]:
start_time = time.time()
%prun -s cumulative test_J()
print("time:", time.time()-start_time)

In [ ]:
import timeit
import marshal

In [ ]:
print(timeit.timeit('marshal.dumps((0,1,2,3,4,5,6,7,8))','import marshal',number = 1000))
print(timeit.timeit('hash((0,1,2,3,4,5,6,7,8))',number = 1000))

In [ ]:
from babiscython_v4_ubuntu import TriaN
from Jfunc_cython_v4 import computeJ as J

kpeak1 = -0.034
kpeak2 = -0.001
kpeak3 = -0.000076
kpeak4 = -0.0000156
kuv1 = 0.069
kuv2 = 0.0082
kuv3 = 0.0013
kuv4 = 0.0000135
kpeak1 = mpfr(str(kpeak1))
kpeak2 = mpfr(str(kpeak2))
kpeak3 = mpfr(str(kpeak3))
kpeak4 = mpfr(str(kpeak4))
kuv1 = mpfr(str(kuv1))
kuv2 = mpfr(str(kuv2))
kuv3 = mpfr(str(kuv3))
kuv4 = mpfr(str(kuv4))

mass1 = -kpeak1 - 1j*kuv1
mass1conj = -kpeak1 + 1j*kuv1
mass2 = -kpeak2 - 1j*kuv2
mass2conj = -kpeak2 + 1j*kuv2
mass3 = -kpeak3 - 1j*kuv3
mass3conj = -kpeak3 + 1j*kuv3
mass4 = -kpeak4 - 1j*kuv4
mass4conj = -kpeak4 + 1j*kuv4

k21 = mpfr(0.5)
k22 = mpfr(0.5)
k23 = mpfr(0.5)

n1 = -1
n2 = 3
n3 = -1

d1=3
d2=3
d3=3

m1=mass1
m2=mass1
m3=mass1


# TriaN(d1,d2,d3,k21,k22,k23,m1,m2,m3)
J(n1,n2,n3,d1,d2,d3,k21,k22,k23)

In [ ]:
str((n1,n2,n3,d1,d2,d3,k21,k22,k23))

In [19]:
lenfdiogo=16
lenfbabis=33

In [20]:
mattemp=np.reshape(np.fromfile('matdiogotobabisnewbasis', np.complex128),(lenfdiogo,lenfbabis))

In [22]:
np.take(mattemp[0],[0])

array([0.0001+0.j])

In [15]:
mattemp[0]

array([0.0001+0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j,
       0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j,
       0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j,
       0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j,
       0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j,
       0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j, 0.    +0.j,
       0.    +0.j, 0.    +0.j, 0.    +0.j])

In [16]:
mattemp_henry=np.reshape(np.fromfile('matdiogotobabisnewfun_henry', np.complex128),(lenfdiogo,lenfbabis))

In [26]:
np.sum(abs(mattemp-mattemp_henry))


1.1211203685061859e-15

In [29]:
i=15
mattemp[i]-mattemp_henry[i]


array([ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  3.23117427e-27+0.00000000e+00j,
        3.23117427e-27+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00-4.93038066e-32j,
        0.00000000e+00+4.93038066e-32j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000